import { GameModel } from "models";

export const games: Omit<GameModel, "id">[] = [
  {
    hostId: "1",
    hostTeam: "Katar",
    guestId: "2",
    guestTeam: "Ekwador",
    date: "2022-11-20T17:00:00+0100",
    stadium: "Al Bayt Stadium, Al-Chaur",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "A",
  },
  {
    hostId: "5",
    hostTeam: "Anglia",
    guestId: "6",
    guestTeam: "Iran",
    date: "2022-11-21T14:00:00+0100",
    stadium: "Stadion Międzynarodowy Chalifa, Ar-Rajjan",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "B",
  },
  {
    hostId: "3",
    hostTeam: "Senegal",
    guestId: "4",
    guestTeam: "Holandia",
    date: "2022-11-21T17:00:00+0100",
    stadium: "Al Thumama Stadium, Doha",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "A",
  },
  {
    hostId: "7",
    hostTeam: "Stany Zjednoczone",
    guestId: "8",
    guestTeam: "Walia",
    date: "2022-11-21T20:00:00+0100",
    stadium: "Ahmed bin Ali Stadium, Ar-Rajjan",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "B",
  },

  {
    hostId: "9",
    hostTeam: "Argentyna",
    guestId: "10",
    guestTeam: "Arabia Saudyjska",
    date: "2022-11-22T11:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "C",
  },
  {
    hostId: "15",
    hostTeam: "Dania",
    guestId: "16",
    guestTeam: "Tunezja",
    date: "2022-11-22T14:00:00+0100",
    stadium: "Education City Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "D",
  },
  {
    hostId: "11",
    hostTeam: "Meksyk",
    guestId: "12",
    guestTeam: "Polska",
    date: "2022-11-22T17:00:00+0100",
    stadium: "Stadium 974",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "C",
  },
  {
    hostId: "13",
    hostTeam: "Francja",
    guestId: "14",
    guestTeam: "Australia",
    date: "2022-11-22T20:00:00+0100",
    stadium: "Stadion Al-Wakrah",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "D",
  },

  {
    hostId: "23",
    hostTeam: "Maroko",
    guestId: "24",
    guestTeam: "Chorwacja",
    date: "2022-11-23T11:00:00+0100",
    stadium: "Al-Khor Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "F",
  },
  {
    hostId: "19",
    hostTeam: "Niemcy",
    guestId: "20",
    guestTeam: "Japonia",
    date: "2022-11-23T14:00:00+0100",
    stadium: "Stadion Chalifa",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "E",
  },
  {
    hostId: "17",
    hostTeam: "Hiszpania",
    guestId: "18",
    guestTeam: "Kostaryka",
    date: "2022-11-23T17:00:00+0100",
    stadium: "Al Thumama Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "E",
  },
  {
    hostId: "21",
    hostTeam: "Belgia",
    guestId: "22",
    guestTeam: "Kanada",
    date: "2022-11-23T20:00:00+0100",
    stadium: "Al Rayyan Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "F",
  },
  {
    hostId: "27",
    hostTeam: "Szwajcaria",
    guestId: "28",
    guestTeam: "Kamerun",
    date: "2022-11-24T11:00:00+0100",
    stadium: "Stadion Al-Wakrah",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "G",
  },
  {
    hostId: "31",
    hostTeam: "Urugwaj",
    guestId: "32",
    guestTeam: "Korea Południowa",
    date: "2022-11-24T14:00:00+0100",
    stadium: "Education City Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "H",
  },
  {
    hostId: "29",
    hostTeam: "Portugalia",
    guestId: "30",
    guestTeam: "Ghana",
    date: "2022-11-24T17:00:00+0100",
    stadium: "Stadium 974",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "H",
  },
  {
    hostId: "25",
    hostTeam: "Brazylia",
    guestId: "26",
    guestTeam: "Serbia",
    date: "2022-11-24T20:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 1",
    group: "G",
  },

  // todo: change host Id below

  {
    hostId: "8",
    hostTeam: "Walia",
    guestId: "6",
    guestTeam: "Iran",
    date: "2022-11-25T11:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "B",
  },
  {
    hostId: "1",
    hostTeam: "Katar",
    guestId: "3",
    guestTeam: "Senegal",
    date: "2022-11-25T14:00:00+0100",
    stadium: "Al Thumama Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "A",
  },
  {
    hostId: "4",
    hostTeam: "Holandia",
    guestId: "2",
    guestTeam: "Ekwador",
    date: "2022-11-25T17:00:00+0100",
    stadium: "Stadion Chalifa",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "A",
  },
  {
    hostId: "5",
    hostTeam: "Anglia",
    guestId: "7",
    guestTeam: "Stany Zjednoczone",
    date: "2022-11-25T20:00:00+0100",
    stadium: "Al-Khor Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "B",
  },
  {
    hostId: "16",
    hostTeam: "Tunezja",
    guestId: "14",
    guestTeam: "Australia",
    date: "2022-11-26T11:00:00+0100",
    stadium: "Stadion Al-Wakrah",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "D",
  },
  {
    hostId: "12",
    hostTeam: "Polska",
    guestId: "10",
    guestTeam: "Arabia Saudyjska",
    date: "2022-11-26T14:00:00+0100",
    stadium: "Education City Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "C",
  },
  {
    hostId: "13",
    hostTeam: "Francja",
    guestId: "15",
    guestTeam: "Dania",
    date: "2022-11-26T17:00:00+0100",
    stadium: "Stadium 974",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "D",
  },
  {
    hostId: "9",
    hostTeam: "Argentyna",
    guestId: "11",
    guestTeam: "Meksyk",
    date: "2022-11-26T20:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "C",
  },
  {
    hostId: "20",
    hostTeam: "Japonia",
    guestId: "18",
    guestTeam: "Kostaryka",
    date: "2022-11-27T11:00:00+0100",
    stadium: "Al Rayyan Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "E",
  },
  {
    hostId: "21",
    hostTeam: "Belgia",
    guestId: "23",
    guestTeam: "Maroko",
    date: "2022-11-27T14:00:00+0100",
    stadium: "Al Thumama Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "F",
  },
  {
    hostId: "24",
    hostTeam: "Chorwacja",
    guestId: "22",
    guestTeam: "Kanada",
    date: "2022-11-27T17:00:00+0100",
    stadium: "Stadion Chalifa",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "F",
  },
  {
    hostId: "17",
    hostTeam: "Hiszpania",
    guestId: "19",
    guestTeam: "Niemcy",
    date: "2022-11-27T20:00:00+0100",
    stadium: "Al-Khor Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "E",
  },
  {
    hostId: "28",
    hostTeam: "Kamerun",
    guestId: "26",
    guestTeam: "Serbia",
    date: "2022-11-28T11:00:00+0100",
    stadium: "Stadion Al-Wakrah",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "G",
  },
  {
    hostId: "32",
    hostTeam: "Korea Południowa",
    guestId: "30",
    guestTeam: "Ghana",
    date: "2022-11-28T14:00:00+0100",
    stadium: "Education City Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "H",
  },
  {
    hostId: "25",
    hostTeam: "Brazylia",
    guestId: "27",
    guestTeam: "Szwajcaria",
    date: "2022-11-28T17:00:00+0100",
    stadium: "Stadium 974",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "G",
  },
  {
    hostId: "29",
    hostTeam: "Portugalia",
    guestId: "31",
    guestTeam: "Urugwaj",
    date: "2022-11-28T20:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 2",
    group: "H",
  },
  {
    hostId: "2",
    hostTeam: "Ekwador",
    guestId: "3",
    guestTeam: "Senegal",
    date: "2022-11-29T16:00:00+0100",
    stadium: "Stadion Chalifa",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "A",
  },
  {
    hostId: "4",
    hostTeam: "Holandia",
    guestId: "1",
    guestTeam: "Katar",
    date: "2022-11-29T16:00:00+0100",
    stadium: "Al-Khor Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "A",
  },
  {
    hostId: "6",
    hostTeam: "Iran",
    guestId: "7",
    guestTeam: "Stany Zjednoczone",
    date: "2022-11-29T20:00:00+0100",
    stadium: "Al Thumama Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "B",
  },
  {
    hostId: "8",
    hostTeam: "Walia",
    guestId: "5",
    guestTeam: "Anglia",
    date: "2022-11-29T20:00:00+0100",
    stadium: "Al Rayyan Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "B",
  },
  {
    hostId: "16",
    hostTeam: "Tunezja",
    guestId: "13",
    guestTeam: "Francja",
    date: "2022-11-30T16:00:00+0100",
    stadium: "Education City Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "D",
  },
  {
    hostId: "14",
    hostTeam: "Australia",
    guestId: "15",
    guestTeam: "Dania",
    date: "2022-11-30T16:00:00+0100",
    stadium: "Stadion Al-Wakrah",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "D",
  },
  {
    hostId: "12",
    hostTeam: "Polska",
    guestId: "9",
    guestTeam: "Argentyna",
    date: "2022-11-30T20:00:00+0100",
    stadium: "Stadium 974",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "C",
  },
  {
    hostId: "10",
    hostTeam: "Arabia Saudyjska",
    guestId: "11",
    guestTeam: "Meksyk",
    date: "2022-11-30T20:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "C",
  },
  {
    hostId: "24",
    hostTeam: "Chorwacja",
    guestId: "21",
    guestTeam: "Belgia",
    date: "2022-12-01T16:00:00+0100",
    stadium: "Al Rayyan Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "F",
  },
  {
    hostId: "22",
    hostTeam: "Kanada",
    guestId: "23",
    guestTeam: "Maroko",
    date: "2022-12-01T16:00:00+0100",
    stadium: "Al Thumama Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "F",
  },
  {
    hostId: "20",
    hostTeam: "Japonia",
    guestId: "17",
    guestTeam: "Hiszpania",
    date: "2022-12-01T20:00:00+0100",
    stadium: "Stadion Chalifa",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "E",
  },
  {
    hostId: "18",
    hostTeam: "Kostaryka",
    guestId: "19",
    guestTeam: "Niemcy",
    date: "2022-12-01T20:00:00+0100",
    stadium: "Al-Khor Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "E",
  },

  {
    hostId: "32",
    hostTeam: "Korea Południowa",
    guestId: "29",
    guestTeam: "Portugalia",
    date: "2022-12-02T16:00:00+0100",
    stadium: "Educatin City Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "H",
  },
  {
    hostId: "30",
    hostTeam: "Ghana",
    guestId: "31",
    guestTeam: "Urugwaj",
    date: "2022-12-02T16:00:00+0100",
    stadium: "Stadion Al-Wakrah",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "H",
  },
  {
    hostId: "26",
    hostTeam: "Serbia",
    guestId: "27",
    guestTeam: "Szwajcaria",
    date: "2022-12-02T20:00:00+0100",
    stadium: "Stadium 974",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "G",
  },
  {
    hostId: "28",
    hostTeam: "Kamerun",
    guestId: "25",
    guestTeam: "Brazylia",
    date: "2022-12-02T20:00:00+0100",
    stadium: "Lusail Stadium",
    result: null,
    round: "Faza grupowa - mecz 3",
    group: "G",
  },

  // groups ended

  {
    hostTeam: "1A",
    guestTeam: "2B",
    date: "2022-12-03T16:00:00+0100",
    stadium: "Al Rayyan Stadium",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1C",
    guestTeam: "2D",
    date: "2022-12-03T20:00:00+0100",
    stadium: "Ahmed bin Ali Stadium, Ar-Rajjan",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1B",
    guestTeam: "2A",
    date: "2022-12-04T16:00:00+0100",
    stadium: "Al Bayt Stadium, Al Chaur",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1D",
    guestTeam: "2C",
    date: "2022-12-04T20:00:00+0100",
    stadium: "Al Thumama Stadium, Doha",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1E",
    guestTeam: "2F",
    date: "2022-12-05T16:00:00+0100",
    stadium: "Al Janoub Stadium, Al Wakra",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1G",
    guestTeam: "2H",
    date: "2022-12-05T20:00:00+0100",
    stadium: "Stadium 974, Doha",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1F",
    guestTeam: "2E",
    date: "2022-12-06T16:00:00+0100",
    stadium: "Education City Stadium, Al Rajjan",
    result: null,
    round: "1/8 finału",
  },
  {
    hostTeam: "1H",
    guestTeam: "2G",
    date: "2022-12-06T20:00:00+0100",
    stadium: "Lusail Stadium, Lusajl",
    result: null,
    round: "1/8 finału",
  },

  // quarter finals

  {
    hostTeam: "1E/2F",
    guestTeam: "1G/2H",
    date: "2022-12-09T16:00:00+0100",
    stadium: "Education City Stadium, Al Rajjan",
    result: null,
    round: "Ćwierćfinał",
  },
  {
    hostTeam: "1A/2B",
    guestTeam: "1C/2D",
    date: "2022-12-09T20:00:00+0100",
    stadium: "Lusail Stadium, Lusajl",
    result: null,
    round: "Ćwierćfinał",
  },
  {
    hostTeam: "1F/2E",
    guestTeam: "1H/2G",
    date: "2022-12-10T16:00:00+0100",
    stadium: "Al Thumama Stadium, Doha",
    result: null,
    round: "Ćwierćfinał",
  },
  {
    hostTeam: "1B/2A",
    guestTeam: "1D/2C",
    date: "2022-12-10T20:00:00+0100",
    stadium: "Al Bayt Stadium, Al Chaur",
    result: null,
    round: "Ćwierćfinał",
  },

  // semi finals

  {
    hostTeam: "Zwycięzca 1 ćwierćfinału",
    guestTeam: "Zwycięzca 2 ćwierćfinału",
    date: "2022-12-13T20:00:00+0100",
    stadium: "Lusail Stadium, Lusajl",
    result: null,
    round: "Półfinał",
  },
  {
    hostTeam: "Zwycięzca 3 ćwierćfinału",
    guestTeam: "Zwycięzca 4 ćwierćfinału",
    date: "2022-12-14T20:00:00+0100",
    stadium: "Al Bayt Stadium, Al Chaur",
    result: null,
    round: "Półfinał",
  },

  // 3rd place

  {
    hostTeam: "Przegrany 1 półfinału",
    guestTeam: "Przegrany 2 półfinału",
    date: "2022-12-17T16:00:00+0100",
    stadium: "Khalifa International Stadium, Al Rajjan",
    result: null,
    round: "Mecz o 3 miejsce",
  },

  // final

  {
    hostTeam: "Zwycięzca 1 półfinału",
    guestTeam: "Zwycięzca 2 półfinału",
    date: "2022-12-18T16:00:00+0100",
    stadium: "Lusail Stadium, Lusajl",
    result: null,
    round: "Finał",
  },
];
